#ifndef SPI_COMMANDS_H
#define SPI_COMMANDS_H

#define SEND_STRING 0x00
#define FINISH_STRING 0x05
#define BEGIN_FILETRANSFER 0x01
#define CONTINUE_FILETRANSFER 0x02
#define FINISH_FILETRANSFER 0x03
#define SEND_WAVEFORMS 0x4

#endif